DECLARE @StartTimeCast DATETIME2(7) = SYSUTCDATETIME();
SELECT TRY_CAST('24/10/1992' AS DATE) AS TestDate
DECLARE @EndTimeCast DATETIME2(7) = SYSUTCDATETIME();

SELECT
    DATEDIFF(MILLISECOND, @StartTimeCast, @EndTimeCast) AS ExecutionTimeCast;